### PR TITLE
Use launcher-backend and launcher-frontend new images

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by vpavlin** [comment]
[test]

**Comment by quintesse** [comment]
@vpavlin could we move this forward?

This PR along with #34 should at least define the staging environments for the new frontend and backend.

Also the new config map can be found here: https://github.com/fabric8-launcher/launcher-openshift-templates/blob/master/openshift/split/launcher-configmap.yaml
Of course that would only be for staging, that's possible, right?

Also, there are several other services defined here that aren't used anymore: https://github.com/openshiftio/saas-launchpad/tree/master/launchpad-services , `missioncontrol` and `nginx` aren't sued anymore. So how do we define that for staging those aren't needed?

**Comment by vpavlin** [comment]
> So how do we define that for staging those aren't needed?

The way saas-* works for staging is slightly different than for promote-to-prod

* promote-to-prod runs through all the services
* staging only deploys the service tied to the build job

So if we remove the unwanted services from CI and delete them from preview cluster, they will never come back



> Of course that would only be for staging, that's possible, right?

Yes, for configMaps we need housekeeping issue if you don't mind:)





> This PR along with #34 should at least define the staging environments for the new frontend and backend.

Problem is that there is a coupling between repo name and service name in CI (these 2 have to be the same, so that the job script finds the right service to deploy) - i.e. even if we merge this, the deployment will fail.

**Comment by vpavlin** [comment]
I cancel my previous statement and ask you to update these PRs - please change the `name:` of those services to match repo name (i.e. `s/launchpad/launcher/`) - it will not influence promote-to-prod as that goes over all services and does not work with names...so the only result is fixed staging;)

**Comment by quintesse** [comment]
@gastaldi are you sure the `environment:` had to be removed too? That's not what I understood from @vpavlin 's comments?

**Comment by gastaldi** [comment]
@quintesse since the service name changed, that won't impact production, therefore I assumed it is safe to remove it

**Comment by vpavlin** [comment]
Just to confirm - this will (well, should..) fix staging, but if you deploy to production, the new version (launcher-*) will go there... promote-to-prod is turned off now, so changes here will not redeploy prod, but make sure you get all the CMs and everything updated before promotions are enabled again

**Pull request merged**
