### PR TITLE
Update backend.yaml

### PR DESCRIPTION
**Pull request by hrishin**
- update backed to https://github.com/fabric8-launcher/launcher-backend/commit/12b33de1f07f81628952ba0c39d93e8aecffa30b

### CODE REVIEW

**Comment by hrishin** [comment]
fixes https://github.com/openshiftio/openshift.io/issues/2527

**Comment by hrishin** [comment]
@gastaldi could we let it go on prod?

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
Thanks

**Pull request merged**
